### PR TITLE
Add regex for pipeline and stage filters

### PR DESCRIPTION
**Pull request by dworlton**
I've updated the single wildcard for pipelines to include full regex on the filters for both pipelines and stages. Unit tests updated and passing. Also tested in live GoCD instance.

### CODE REVIEW

**Comment by arvindsv** [comment]
I don't really use this. But, won't this break all existing setups?

**Comment by dworlton** [comment]
> I don't really use this. But, won't this break all existing setups?

@arvindsv You are right on that point. I will need to re-enable the "*" only code for backwards compatibility. I appreciate the feedback. I'll add that back in. Other than the "*" only wildcard I don't see any other breaking changes, do you?

**Comment by dworlton** [comment]
I've amended my change to put back the * only functionality and the related unit test. This change should now be backwards compatible, but add the regex feature if users choose to apply it.

**Comment by arvindsv** [comment]
@dworlton I made some small changes to the filter code. It looks like [this now](https://github.com/arvindsv/email-notifier/blob/8689132d3da9bd2c16117ac6b34cc53f671234d9/src/com/tw/go/plugin/Filter.java). And is part of [this branch](https://github.com/arvindsv/email-notifier/tree/dworlton-master), where the tests actually run (!). Take a look when you have the time, and let me know what you think and I can merge both our changes in.

This plugin needs a maintainer. I don't think anyone is maintaining it.

**Comment by arvindsv** [comment]
Oh, also, you'll need to sign the CLA, if you want this to be merged. Thank you!

**Comment by dworlton** [comment]
This plugin's functionality only augments the GoCD email function by allowing e-mail without authentication and e-mail to a distribution list instead of to the logged-in individual. It seems like it would not be too much effort to merge it into the main GoCD email functions.

**Comment by arvindsv** [comment]
I think the idea was to allow this to be more flexible, by providing more control over the content and over the kinds of connections it can make. I think it has a place.

It's true that the default email functionality could be improved too, of course.

**Comment by dworlton** [comment]
@arvindsv I finally have contribution approval from my employer. This is now ready for your final review, conflict resolution, etc. Let me know if anything further is needed. Thanks!

**Comment by arvindsv** [comment]
@dworlton Yay! Can you incorporate the changes from [this commit](https://github.com/arvindsv/email-notifier/commit/6c18a4e59e404cece57d8dfcdb2a55970900eab6) - just cherry-pick it and resolve conflicts? I'll then take a look at it and merge it in soon.

**Comment by arvindsv** [comment]
Hmm. I see I had made some changes to make the tests run and there were other changes to do the same, meanwhile. Maybe we don't need my changes. Let me take a quick look.

**Comment by arvindsv** [comment]
@dworlton I've made some of those changes again, which remove powermock, etc. Can you resolve conflicts, please? If possible, incorporate my changes from https://github.com/arvindsv/email-notifier/commit/6c18a4e59e404cece57d8dfcdb2a55970900eab6 on top of your changes. If not, that's ok. I'll do it later.

**Comment by arvindsv** [comment]
It would probably be useful for you to test it on a live instance, again. Thank you!

**Comment by dworlton** [comment]
@arvindsv , I am struggling with this Maven > Gradle transition. I don't have much Gradle experience, but using the standard gradle project in Intellij IDEA I am getting the following error:
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating script.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:206)
	at org.gradle.configuration.DefaultScriptTarget.addConfiguration(DefaultScriptTarget.java:74)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:211)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:109)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:38)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:68)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at build_9z5xxzvrugtmv4h2oqlnynmye.run(C:\Users\dw13267\Documents\Development\OSS\gocd\email-notifier\build.gradle:72)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 106 more
Caused by: org.gradle.api.GradleScriptException: fatal: ambiguous argument '%s': unknown revision or path not in the working tree.

Any ideas or tips to fix this? I can't really fix the conflicts without getting gradle working properly. Thanks!

**Comment by arvindsv** [comment]
@dworlton No problem. Can you take a look [at this](https://github.com/gocd-contrib/email-notifier/compare/master...arvindsv:pr-20-fix-conflicts?expand=1) and tell me if it looks ok? If so, I can close this PR, open another and merge it. It has your commits, with the conflicts fixed.

I'm not sure what's happening in IntelliJ. I have IntelliJ 2018.3 and it works fine. Are you able to run `./gradlew test` from the command-line?

**Comment by arvindsv** [comment]
Or, you can force push that branch over here. Instead of us opening another PR.

**Comment by dworlton** [comment]
@arvindsv: This will not build with ./gradlew test. Again, I don't have gradle experience, but closer examination of the stacktrace gives me
`plugin_tasks_6lllhidqv4eg1pvldv98h6vp9.run(C:\Users\dw13267\Documents\Development\OSS\gocd\email-notifier\plugin-tasks.gradle:236)`

which points at the github configuration. It seems this configuration expects system environment variables which I do not have. Especially troublesome seems to be line 244:
`prerelease = !"No".equalsIgnoreCase(System.getenv('PRERELEASE'))`

If I understand the groovy syntax correctly this will evaluate to true always if I do not have a system environment variable called PRERELEASE. I suspect this might be causing me issues. I may try putting in some debug logs to identify what the git command ends up looking like, but as I can't get this to build I don't feel comfortable pushing it. If you'd like to open a new pull request with your code and merge that I think it would be fine. What you have in that branch looks good to me.

I'll let you know if I have success debugging this. There might be a need to include a change to the gradle scripts (or documentation) if this can't work straight from checkout for contributors.

**Comment by arvindsv** [comment]
@dworlton I opened a new PR and merged it. I tried it on Windows, in the CMD prompt. I had to make a [small change](https://github.com/gocd-contrib/email-notifier/pull/22/files#diff-2f248da3a33a318a3e5ff33f508a8efbR50) to make it work.

With that change, I was able to run: `./gradlew test` and it worked. Not sure if it works on IntelliJ, on Windows, yet.

The line you pointed to should not be a problem (`PRERELEASE` etc). I think it is used for publishing a new plugin release to GitHub.

**Comment by dworlton** [comment]
@arvindsv , thank you for taking care of this. I've cloned the new merged version, `.\gradlew test` works from Windows and it also builds properly now from within IntelliJ IDEA 2018.1.5 (Ultimate) on Windows.

**Comment by arvindsv** [comment]
@dworlton You're welcome. Glad it worked. :) Thank you for taking the time and making those changes. It's always good to see.

**Pull request merged**
